# src/app/services/report_service.py

from __future__ import annotations

import logging
from pathlib import Path
from typing import List, Optional

from sqlalchemy.orm import Session

from src.core.settings import get_settings
from src.db.models.pdf_report import PdfReport
from src.db.models.scan import Scan

# Standard logger for tracking audit deletions
logger = logging.getLogger(__name__)
settings = get_settings()


def list_reports_for_user(db: Session, user_id: int) -> List[PdfReport]:
    """
    Return all PDF reports for a given user, newest first.
    """
    return (
        db.query(PdfReport)
        .filter(PdfReport.user_id == user_id)
        .order_by(PdfReport.created_at.desc())
        .all()
    )


def get_report_for_user(
    db: Session,
    report_id: int,
    user_id: int,
) -> Optional[PdfReport]:
    """
    Fetch a specific report ensuring it belongs to the authenticated user.
    """
    return (
        db.query(PdfReport)
        .filter(PdfReport.id == report_id, PdfReport.user_id == user_id)
        .first()
    )


def create_report_record(
    db: Session,
    *,
    user_id: int,
    scan_id: int,
    file_path: str,
) -> PdfReport:
    """
    Create a PdfReport DB record. Assumes the file is already generated by the worker.
    """
    report = PdfReport(
        user_id=user_id,
        scan_id=scan_id,
        file_path=file_path,
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


def delete_report_for_user(
    db: Session,
    report_id: int,
    user_id: int,
) -> bool:
    """
    Delete report record and the physical file from shared Docker storage.
    Standardized to look in /app/pdf_reports for cross-container consistency.
    """
    report = get_report_for_user(db, report_id=report_id, user_id=user_id)
    if not report:
        logger.warning(f"Delete attempt failed: Report {report_id} not found for user {user_id}")
        return False

    # ✅ PATH RESOLUTION: Use filename only to prevent double-nesting errors
    filename = Path(report.file_path).name
    
    # Use settings if available, otherwise fallback to standard Docker volume path
    storage_dir = Path(getattr(settings, 'PDF_OUTPUT_DIR', '/app/pdf_reports'))
    physical_path = storage_dir / filename

    if physical_path.exists():
        try:
            physical_path.unlink()
            logger.info(f"Successfully unlinked physical PDF: {physical_path}")
        except Exception as e:
            logger.error(f"OS Error unlinking {physical_path}: {str(e)}")
            # We continue to DB deletion so the UI doesn't get stuck with a broken record
    else:
        logger.warning(f"File system mismatch: {physical_path} not found. Deleting DB record only.")

    db.delete(report)
    db.commit()
    return True


def get_scan_owned_by_user(
    db: Session,
    *,
    scan_id: int,
    user_id: int,
) -> Optional[Scan]:
    """
    Helper: verify scan ownership before report generation.
    """
    return (
        db.query(Scan)
        .filter(Scan.id == scan_id, Scan.user_id == user_id)
        .first()
    )